sonar.projectKey=vinod-itmethods_sonar-codefix-demo
sonar.organization=itmethods-inc
sonar.projectName=sonar-codefix-demo
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/tests/**,**/.git/**,**/node_modules/**,.sonarlint/**,.vscode/**,.github/**
sonar.python.version=3
